### ISSUE TITLE
Q3/Q4 2019 Planning

### ISSUE THREAD

**Issue by ghost** [libp2p/libp2p#77] opened 2019-06-12 23:10 UTC
Background video (5 min @ 1X speed):  [https://youtu.be/7Hh3enUu0H0](https://youtu.be/7Hh3enUu0H0)

Let's use this thread to discuss and post subsequent artifacts like roadmaps and OKRs.  By the time this issue is closed, we should have a realistic plan for the second half of 2019, and supporting documents showing how we'll achieve it.

EDIT:  This issue will be closed by a PR that adds a `ROADMAP.md` file to this repo covering the remainder of 2019 in detail.

**Comment by mxinden** [comment] 2021-06-18 11:42
Closing here as a duplicate of https://github.com/libp2p/libp2p/issues/68.

**Closed as completed by mxinden** 2021-06-18 11:42 UTC
